#!/bin/sh
if [ $(id -u) != 0 ]; then
	exec sudo $0 "$@"
	exit 1
fi

cd /media/space/openmandriva/abf-downloads
BACKUP_VERSION_SPECIFICS=true
if [ "$1" = "-c" -o "$1" = "--continue" ]; then
	BACKUP_VERSION_SPECIFICS=false
	shift
fi
VERSION="$1"
if [ -z "$VERSION" ]; then
	echo "Usage: $0 VERSION"
	exit 1
fi

if $BACKUP_VERSION_SPECIFICS; then
	if [ -d "$VERSION" ]; then
		rm -rf ${VERSION}_backup
		cd ${VERSION}
		ls repository/*/*/*/{{lsb,distro}-release,om-midna-sddm}* |while read f; do
			mkdir -p ../${VERSION}_backup/$(dirname $f)
			cp $f ../${VERSION}_backup/$f
		done
		cd ..
	fi
fi
rsync -azv --progress --partial --delete --delete-excluded --exclude armv7hnl/ --exclude i686/ --exclude riscv64/ --exclude testing/ --exclude container/ rolling/* ${VERSION}/
rm -f ${VERSION}/repository/*/*/*/{{lsb,distro}-release,om-midna-sddm}*
cp -a ${VERSION}_backup/* ${VERSION}

for ARCH in SRPMS aarch64 x86_64 znver1; do
	for REPO in main unsupported restricted non-free debug_main debug_unsupported debug_restricted debug_non-free; do
		echo "Rebuilding metadata for $ARCH $REPO"
		docker run --rm -v /media/space/openmandriva/abf-downloads:/share/platforms openmandriva/createrepo:aarch64 /share/platforms/${VERSION}/repository/$ARCH/$REPO/release/ &
		createrepo_c /media/space/openmandriva/abf-downloads/${VERSION}/repository/$ARCH/$REPO/testing/ &
		createrepo_c /media/space/openmandriva/abf-downloads/${VERSION}/repository/$ARCH/$REPO/updates/ &
	done
done
wait
